baseURL = 'https://bramadityaw.github.io/blog'
languageCode = 'en-us'
title = 'dityaw.dump'
theme = 'tale-hugo'

[menu]
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    title = "Tags"
    url = "/tags/"
    weight = 0

[params]
  [params.author]
    name = 'Bramaditya'
    url = 'https://www.bramadityaw.github.io'
  [params.links]
    GitHub = 'https://github.com/bramadityaw'
    Linkedin = 'https://linkedin.com/in/r-bramaditya'
