baseURL = 'https://bramadityaw.github.io/blog'
languageCode = 'en-us'
title = 'dityaw.dump'
theme = 'github.com/EmielH/tale-hugo/'

[author]
  name = 'Bramaditya'
  url = 'https://www.bramadityaw.github.io'
